services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Twig\ContentInfoByLocationIdExtension: ~

    App\Twig\SearchResultExtractorExtension: ~

    App\Twig\PremiumContentExtension:
        arguments:
            $allowedUserGroupsLocationIds: '%app.premium_content.allowed_user_groups.location_ids%'

    App\Twig\ContentPaginationExtension: ~

    App\Twig\AppLayoutExtension:
        arguments:
            $renderers: !tagged { tag: layout.renderer, index_by: key }
